---
# requirements
requirements_packages:
  - bzip2
  - curl

# archives
stage3_archive: /tmp/stage3-latest.tar.bz2

portage_archive: /tmp/portage-latest.tar.bz2

default_mirror: http://distfiles.gentoo.org/

# partitioning
main_disk_path: /dev/nvme0n1

# mount
gentoo_chroot: /mnt/install

chroot_dirs:
  - boot
  - dev
  - sys
  - proc
  - usr

# system
chroot_cmd: "chroot {{ gentoo_chroot }} bash -c"

gentoo_timezone: Europe/Paris

gentoo_profile: default/linux/amd64/17.0

gentoo_portage_kind:
  - keywords
  - license
  - use

base_packages_use:
  - sys-apps/util-linux static-libs
  - sys-boot/grub:2 device-mapper

base_packages_keyword: []

base_packages:
  - cryptsetup
  - dhcpcd
  - genkernel
  - gentoo-sources
  - gentoolkit
  - grub:2
  - linux-firmware
  - openssh
  - openssl
  - sudo

gentoo_root_passwd: coconut

gentoo_hostname: chat
