version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.17.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      default:
        aliases:
          - elasticsearch
  mediawiki-web:
    environment:
      MW_ELASTIC_HOST: elasticsearch
      MW_ELASTIC_PORT: 9200
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local