---
# TODO:
# keychain
# hexchat
# virtualenvwrapper
# git prompt

- name: configure | group
  group: name="{{ group }}" state=present

- name: configure | user
- user: name="{{ user }}" comment="added by ansible" group="{{ group }}" groups="{{ groups }}"

- name: configure | home basic file
  template:
    src: "{{ item.src }}"
    dest: "{{ home }}/{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - {"src": "home/bashrc.j2", "dest": ".bashrc"}
    - {"src": "home/gitconfig.j2", "dest": ".gitconfig"}
    - {"src": "home/gitignore_global.j2", "dest": ".gitignore_global"}
    - {"src": "home/vimrc.j2", "dest": ".vimrc"}
    - {"src": "home/pentadactylrc.j2", "dest": ".pentadactylrc"}

- name: configure | i3 | dir
  file:
    path: "{{ home }}/.i3"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
    state: directory

- name: configure | i3 | py3status / config
  template:
    src: "i3/{{ item }}"
    dest: "{{ home }}/.i3/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - config.j2
    - i3status.conf.j2

- name: configure | xinit
  template:
    src: "xinitrc.j2"
    dest: "{{ home }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: configure | slim | conf
  template:
    src: "slim.conf.j2"
    dest: "/etc/slim.conf"
    owner: root
    group: root
