---
- name: install | portage directory
  file: path=/etc/portage/package.{{ item }} state=directory mode=0755 owner=root group=root
  with_items:
    - keywords
    - license
    - mask
    - use

- name: install | portage use/keywords file
  template: src="gentoo/{{ item }}" dest=/etc/portage/package.{{ item }}/lujeni_settings.{{ item }}
  with_items:
    - keywords
    - license
    - use

- name: install | role's package
  portage: package="{{ item }}" newuse=yes state=installed
  with_items: "{{ settings_packages }}"

- name: install | role's package pip
  pip: name="{{ item }}"
  with_items: "{{ settings_packages_pip }}"
