- name: docker | data
  file:
    path: "{{ home }}/docker/{{ item[0] }}/{{ item[1] }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0755
    state: directory
  with_nested:
    - ["data", "dockerfiles"]
    - "{{ docker_images }}"

- name: docker | deploy
  template:
    src: "docker/{{ item }}/Dockerfile.j2"
    dest: "{{ home }}/docker/dockerfiles/{{ item }}/Dockerfile"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644
  loop: "{{ docker_images }}"
  
- name: docker | deploy | mattermost extra directory
  file:
    path: "{{ home }}/docker/data/mattermost-desktop/{{ item }}"
    group: "{{ group }}" # NOTE: chrome user in Docker image
    owner: "{{ user }}" # NOTE: chrome user in Docker image
    mode: 0755
    state: directory
  loop:
    - config
    - downloads
   
- name: docker | deploy | chrome extra directory
  file:
    path: "{{ home }}/docker/data/chrome/{{ item }}"
    group: "999" # NOTE: chrome user in Docker image
    owner: "999" # NOTE: chrome user in Docker image
    mode: 0755
    state: directory
  loop:
    - data
    - downloads
 
- name: docker | deploy | chrome local font
  template:
    src: "docker/chrome/local.conf"
    dest: "{{ home }}/docker/dockerfiles/chrome/local.conf"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644

- name: docker | deploy | chrome seccomp
  template:
    src: "docker/chrome/seccomp.json"
    dest: "/etc/docker/seccomp-chrome.json"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644

- name: docker | deploy | chrome volume rights
  file:
    path: "{{ home }}/docker/data/chrome/"
    group: "999"
    owner: "{{ user }}"
    mode: 0775

- name: docker | deploy | ykperso
  template:
    src: "docker/ykperso/entrypoint.sh"
    dest: "{{ home }}/docker/dockerfiles/ykperso/entrypoint.sh"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644

- name: docker | build
  shell: |
    cd {{ home }}/docker/dockerfiles/{{ item }} && \
    docker build . -t {{ docker_repo_prefix }}/{{ item }}:{{ docker_images_version }}
  loop: "{{ docker_images }}"
