---
- include: system.yml
  tags:
    - settings
    - settings_system

- include: x.yml
  tags:
    - settings
    - settings_x
    
- include: docker.yml
  tags:
    - settings
    - settings_docker

- include: post.yml
  tags:
    - settings
    - settings_post
