- name: system | group
  group:
    name: "{{ group }}"
    state: present

- name: system | user
  user:
    name: "{{ user }}"
    comment: "added by ansible"
    group: "{{ group }}"
    groups: "{{ other_groups }}"
    state: present
    append: yes

- name: system | portage directory
  file:
    path: "/etc/portage/package.{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
    - keywords
    - license
    - mask
    - use

- name: system | portage use/keywords file
  template:
    src: "etc/portage/package.{{ item }}.j2"
    dest: /etc/portage/package.{{ item }}/settings.{{ item }}
    mode: 0644
    owner: root
    group: root
  loop:
    - keywords
    - license
    - use

- name: system | hostname
  lineinfile:
    dest: /etc/conf.d/hostname
    regexp: ^hostname=
    line: 'hostname="{{ inventory_hostname }}"'
    state: present
  register: hostname

- name: system | refresh hostname
  command: "hostname {{ inventory_hostname }}"
  when: hostname.changed

- name: system | keymaps
  lineinfile:
    dest: /etc/conf.d/keymaps
    regexp: ^keymap=
    line: 'keymap="{{ system_keymap }}"'
    state: present

- name: system | set up locale(s)
  locale_gen:
    name: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
  loop: "{{ system_default_locale.locale_gen }}"

- name: system | generate locale(s)
  shell: "locale-gen"
  changed_when: False

- name: system | set system-wide locale via eselect
  shell: "eselect locale set {{ system_default_locale.eselect }}"
  changed_when: False

- name: system | update environment
  command: env-update
  changed_when: False

- name: system | nsswitch
  template:
    src: etc/nsswitch.j2
    dest: /etc/nsswitch.conf
    group: root
    owner: root
    mode: 0644

- name: system | ntp-client
  template:
    src: etc/conf.d/ntp-client.j2
    dest: /etc/conf.d/ntp-client
    group: root
    owner: root
    mode: 0644

- name: system | ntpd
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
    group: root
    owner: root
    mode: 0644

- name: system | nscd.conf
  template:
    src: etc/nscd.conf.j2
    dest: /etc/nscd.conf
    group: root
    owner: root
    mode: 0644

- name: system | make.conf
  template:
    src: etc/portage/make.conf.j2
    dest: /etc/portage/make.conf
    group: root
    owner: root
    mode: 0644

- name: system | portage world
  template:
    src: var/lib/portage/world.j2
    dest: /var/lib/portage/world
    group: root
    owner: root
    mode: 0644

- name: system | sets directory
  file:
    path: /etc/portage/sets
    group: root
    owner: root
    mode: 0755
    state: directory

- name: system | sets
  template:
    src: etc/portage/sets/core.j2
    dest: /etc/portage/sets/core
    group: root
    owner: root
    mode: 0644
    
- name: system | add overlay
  layman:
    name: ahyangyi-overlay # youcompleteme
    state: updated

- name: system | install packages
  portage:
    package: "{{ item }}"
    newuse: yes
    state: installed
  loop: "{{ system_packages }}"

- name: system | genkernel
  template:
    src: etc/genkernel.conf.j2
    dest: /etc/genkernel.conf
    group: root
    owner: root
    mode: 0644

- name: system | Networkmanager
  template:
    src: etc/NetworkManager/NetworkManager.conf.j2
    dest: /etc/NetworkManager/NetworkManager.conf
    group: root
    owner: root
    mode: 0644

- name: system | smux
  template:
    src: usr/bin/smux.j2
    dest: /usr/bin/smux
    group: root
    owner: root
    mode: 0775
