- name: partitioning | ensure partition umount
  shell: "umount -lf {{ gentoo_chroot }}"
  failed_when: False

- name: partitioning | ensure cryptsetup close
  shell: " cryptsetup luksClose root"
  failed_when: False

# TODO: add parted steps (need fs_type support)

# TODO: check luks module from Ansible
- name: partitioning | deploy luks key
  copy:
    src: luks
    dest: /tmp/key-file
    owner: root
    group: root
    mode: 0400

- name: partitioning | create luks container
  shell: "cryptsetup luksFormat --type luks1 -c aes-xts-plain64 -s 512 -h sha512 -d /tmp/key-file --batch-mode {{ main_disk_path }}p3"

- name: partitioning | open luks
  shell: "cryptsetup luksOpen -d /tmp/key-file {{ main_disk_path }}p3 root"

- name: partitioning | format boot partition
  shell: "mkfs.vfat -F 32 {{ main_disk_path }}p2"

- name: partitioning | format root partition
  shell: "mkfs.ext4 /dev/mapper/root"
