name: Continuous Integration (CI)
on: pull_request
env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1
jobs:
  clean-git-history-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check history.
        run: earthly --ci +clean-git-history-checking --from_reference "origin/${{ github.base_ref }}"
  go-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check formatting.
        run: earthly --ci +check-go-formatting
  sh-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check formatting.
        run: earthly --ci +check-sh-formatting
  yaml-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check formatting.
        run: earthly --ci +check-yaml-formatting
  go-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check linting.
        run: earthly --ci +go-linting
  sh-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check linting.
        run: earthly --ci +sh-linting
  module-tidying:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check module.
        run: earthly --ci +check-module-tidying
  compiling:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check compiling.
        run: earthly --ci +compiling-linux-amd64
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Check unit testing.
        run: earthly --ci +unit-testing
