name: GitHub Actions Workflows
on: pull_request
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.7.7.
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Checkout code.
        uses: actions/checkout@v3
      - name: Lint GitHub Actions Workflows.
        run: earthly +github-actions-workflows-linting
