name: Mirroring
on:
  # Mirroring after releasing, so tags are pushed.
  workflow_run:
    workflows: ["Releasing"]
    # Only mirroring on the default branch, otherwise dead branches are pushed and never cleaned up.
    branches: [main]
    types: [completed]
jobs:
  GitLab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirroring.
        run: ./ci/mirroring.sh
        env:
          GITLAB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITLAB_PERSONAL_ACCESS_TOKEN }}
