# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: License chooser and license display code
# All technologies used
technologies: Python, bash
# Whether this repository should be featured on the CC Open Source site
featured: false
