---
- name: configure | ansible into nginx group
  user: name=ansible groups=nginx append=yes

- name: configure | maintenance directory
  file: path="{{ nginx_maintenance_dir }}" state=directory owner=nginx group=root mode=0750

- name: configure | nginx.d directory
  file: path=/etc/nginx.d/ state=directory owner=nginx group=nginx mode=0755

- name: configure | localhost directory
  file: path=/etc/nginx.d/localhost/ state=directory owner=nginx group=nginx mode=0775

- name: configure | localhost conf
  template: src=nginx.d/localhost.j2 dest=/etc/nginx.d/localhost/localhost.conf owner=nginx group=nginx mode=0644
  notify: reload service nginx

- name: configure | www directory
  file: path=/var/www/ state=directory owner=nginx group=nginx mode=0775

- name: configure | mime.types
  template: src=mime.types dest=/etc/nginx/mime.types owner=nginx group=nginx mode=0644
  notify: reload service nginx

- name: configure | nginx.conf
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf backup=yes owner=nginx group=nginx mode=0644
  notify: reload service nginx

- name: configure | tuning open file limits
  template: src=limits.j2 dest=/etc/security/limits.d/nginx.conf owner=root group=root mode=0644

- name: configure | default runlevel and start it
  service: name=nginx runlevel=default enabled=yes state=started
