---
- name: configure | uwsgi conf.d
  template:
    src: "uwsgi.j2"
    dest: "/etc/conf.d/uwsgi"
    owner: root
    group: root
    mode: 0644

- name: configure | default rights
  file: path=/etc/uwsgi.d state=directory owner=root group=nginx mode=0775

- name: configure | default spool directory
  file: path=/var/spool/uwsgi/ state=directory owner=root group=nginx mode=0775

- name: configure | add service to default runlevel
  service: name=uwsgi runlevel=default enabled=yes
