---
- name: install | portage use/keywords
  template: src={{ item }} dest=/etc/portage/package.{{ item }}/gentoo_uwsgi.{{ item }}
  with_items:
    - keywords
    - use

- name: install | role's package
  portage: package="{{ item }}" state=installed
  with_items:
    - "{{ uwsgi_packages }}"
