name: Deploy repository to CDNs

on:
  push:
    branches:
      - yt-dlp
  workflow_dispatch:
    inputs: {}

jobs:
  netlify:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Set up Netlify
        run: npm install netlify-cli -g
      - name: Build and deploy
        run: |
          netlify build
          netlify deploy --prod
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          github-comment: false 
