- name: "archives | check for {{ stage3_archive }} on disk"
  stat:
    path: "{{ stage3_archive }}"
  register: ondisk_stage3

- name: "archives | check for {{ portage_archive }} on disk"
  stat:
    path: "{{ portage_archive }}"
  register: ondisk_portage

- name: archives | check for the latest stage3 archive online (via curl + awk)
  shell: "curl http://distfiles.gentoo.org/releases/amd64/autobuilds/latest-stage3.txt 2>/dev/null | awk '$0 !~ /^#/ { print $1; exit; }'"
  register: online_stage3
  when: ondisk_stage3 is defined and not ondisk_stage3.stat.exists

- name: archives | download the latest stage3 archive
  get_url:
    url: "{{ default_mirror }}/releases/amd64/autobuilds/{{ online_stage3.stdout }}"
    dest: "{{ stage3_archive }}"
    group: root
    owner: root
    mode: 0644
  when: not ondisk_stage3.stat.exists

- name: archives | download the latest portage archive
  get_url:
    url: "{{ default_mirror }}/releases/snapshots/current/portage-latest.tar.bz2"
    dest: "{{ portage_archive }}"
    group: root
    owner: root
    mode: 0644
  when: portage_archive is defined and not ondisk_portage.stat.exists
