---
- include: requirements.yml
  tags:
    - install
    - install_requirements

- include: archives.yml
  tags:
    - install
    - install_archives

- include: partitioning.yml
  tags:
    - install
    - install_partitioning

- include: mount.yml
  tags:
    - install
    - install_mount

- include: system.yml
  tags:
    - install
    - install_system
