- name: "mount | create {{ gentoo_chroot }} directory"
  file:
    path: "{{ gentoo_chroot }}"
    state: directory

- name: "mount | create {{ chroot_dirs }} directories"
  file:
    path: "{{ gentoo_chroot }}/{{ item }}"
    state: directory
  loop: "{{ chroot_dirs }}"

- name: "mount | mount /dev/mapper/root in {{ gentoo_chroot }}"
  mount:
    name: "{{ gentoo_chroot }}"
    src: "/dev/mapper/root"
    fstype: ext4
    state: mounted

- name: "mount | mount {{ main_disk_path }}p2 in {{ gentoo_chroot }}/boot"
  mount:
    name: "{{ gentoo_chroot }}/boot"
    src: "{{ main_disk_path }}p2"
    fstype: vfat
    state: mounted

- name: "mount | extract {{ stage3_archive }} in {{ gentoo_chroot }}"
  unarchive:
    src: "{{ stage3_archive }}"
    dest: "{{ gentoo_chroot }}"
    remote_src: True

- name: "mount | extract {{ portage_archive }} in {{ gentoo_chroot }}/usr"
  unarchive:
    src: "{{ portage_archive }}"
    dest: "{{ gentoo_chroot }}/usr"
    remote_src: True

- name: "mount | bind mount /{{ item }} in {{ gentoo_chroot }}/{{ item }}"
  mount:
    name: "{{ gentoo_chroot }}/{{ item }}"
    src: "/{{ item }}"
    fstype: "{{	item }}"
    opts: rbind
    state: mounted
  with_items:
    - 'proc'
    - 'dev'
    - 'sys'
    - 'run'
