- name: system | copy over resolv.conf
  shell: "cp -L /etc/resolv.conf {{ gentoo_chroot }}/etc/"

- name: system | repos.conf directory
  file:
    dest: "{{ gentoo_chroot }}/etc/portage/repos.conf/"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: system | copy over repos.conf
  shell: "cp -L {{ gentoo_chroot }}/usr/share/portage/config/repos.conf {{ gentoo_chroot }}/etc/portage/repos.conf/gentoo.conf"

- name: system | update portage
  shell: "{{ chroot_cmd }} emerge-webrsync"

- name: system | configure zoneinfo
  shell: "{{ chroot_cmd }} cp /usr/share/zoneinfo/{{ gentoo_timezone }} /etc/localtime; echo {{ gentoo_timezone }} > /etc/timezone"

- name: system | configure system profile via eselect
  shell: "{{ chroot_cmd }} eselect profile set {{ gentoo_profile }}"

- name: system | read news
  shell: "{{ chroot_cmd }} eselect news read"

- name: system | portage directory
  file:
    dest: "{{ gentoo_chroot }}/etc/portage/package.{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  loop: "{{ gentoo_portage_kind }}"

- name: system | portage files
  template:
    src: "etc/portage/{{ item }}.j2"
    dest: "{{ gentoo_chroot }}/etc/portage/package.{{ item }}/gentoo_install.{{ item }}"
    mode: 0644
    owner: root
    group: root
  loop: "{{ gentoo_portage_kind }}"

- name: system | make.conf
  template:
    src: "etc/portage/make.conf.j2"
    dest: "{{ gentoo_chroot }}/etc/portage/make.conf"
    mode: 0644
    owner: root
    group: root

- name: system | install bare minimum packages
  shell: "{{ chroot_cmd }} 'source /etc/profile; emerge -q --backtrack=30 -1 {{ base_packages|join(' ')}}'"

- name: system | configure root password
  shell: "{{ chroot_cmd }} 'source /etc/profile; echo root:{{ gentoo_root_passwd }} | /usr/sbin/chpasswd'"

- name: system | copy over hostname file
  template:
    src: etc/conf.d/hostname.j2
    dest: "{{ gentoo_chroot }}/etc/conf.d/hostname"
    mode: 0644
    owner: root
    group: root

- name: system | copy fstab
  template:
    src: etc/fstab.j2
    dest: "{{ gentoo_chroot }}/etc/fstab"
    mode: 0644
    owner: root
    group: root

- name: system | create kernels directory
  file:
    dest: "{{ gentoo_chroot }}/etc/kernels"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: system | copy kernel file
  copy:
    src: kernel
    dest: "{{ gentoo_chroot }}/etc/kernels/kernel"
    mode: 0644
    owner: root
    group: root

- name: system | build kernel, modules and initramfs via genkernel and install them
  shell: "{{ chroot_cmd }} 'source /etc/profile; genkernel --luks --lvm --no-zfs --kernel-config=/etc/kernels/kernel all'"

- name: system | copy over grub2 configuration file
  template:
    src: etc/default/grub.j2
    dest: "{{ gentoo_chroot }}/etc/default/grub"
    mode: 0644
    owner: root
    group: root

- name: system | install grub with efi
  shell: "{{ chroot_cmd }} 'source /etc/profile; grub-install --efi-directory=/boot --target=x86_64-efi' {{ main_disk_path }}"

- name: system | generate grub config
  shell: "{{ chroot_cmd }} 'source /etc/profile; grub-mkconfig -o /boot/grub/grub.cfg'"

- name: system | reboot
  shell: "init 6"
