---
- name: install | portage use/keywords
  template: src={{ item }} dest=/etc/portage/package.{{ item }}/gentoo_blog.{{ item }}
  with_items:
    - use

- name: install | role's package
  portage: package="{{ item }}" newuse=yes state=installed
  with_items:
    - "{{ blog_packages }}"

- stat: path="{{ blog_root_dir }}"
  register: blog_exist

- stat: path="{{ blog_root_dir }}/themes/{{ blog_theme }}"
  register: blog_theme_stat

- name: install | hugo site
  shell:  "hugo new site {{ blog_root_dir }}"
  when: "{{ blog_exist is defined and not blog_exist.stat.exists }}"
  register: blog_create

- name: install | hugo theme
  git: repo="https://github.com/digitalcraftsman/hugo-cactus-theme.git" dest="{{ blog_root_dir }}/themes/{{ blog_theme }}"
  when: "{{ blog_theme is defined and not blog_theme_stat.stat.exists }}"
