---
uwsgi_packages:
  - www-servers/uwsgi

uwsgi_use:
  - 'www-servers/uwsgi python python_gevent uwsgi_plugins_syslog spooler syslog -uwsgi_plugins_rrdtool -zeromq'

uwsgi_use_php: False

uwsgi_keywords:
  - www-servers/uwsgi

uwsgi_emperor_path: /etc/uwsgi.d/*/*/*

uwsgi_user: nginx

uwsgi_emperor_group: nginx

uwsgi_fastrouter_processes: 5

uwsgi_spool_directory: []
