version: '2'
services:
  memcached:
    image: memcached:1.4
    ports:
      - "11211:11211"

  ia_webserver_memcached:
    build:
      context: .
      args:
        GIT_BRANCH: master
    ports:
      - "8107:8000"
    links:
      - memcached
    container_name: ia-webserver-memcached

  memcached_ui:
    image: alphayax/phpmemcachedadmin
    ports:
      - "11212:80"
    volumes:
      - ./memcached-ui.config.php:/var/www/html/Config/Memcache.php
    links:
      - memcached
    container_name: memcached-ui
