---
- name: install | portage use/keywords
  template: src={{ item }} dest=/etc/portage/package.{{ item }}/gentoo_nginx.{{ item }}
  with_items:
    - keywords
    - use

- name: install | check if user exists
  shell: /usr/bin/getent group | awk -F":" '{print $1}'
  register: etc_groups
  changed_when: False
  always_run: True

- name: install | create group
  group: name=nginx gid={{ nginx_gid }} system=yes state=present
  when: "'nginx' not in etc_groups.stdout_lines"

- name: install | create user
  user: name=nginx uid={{ nginx_uid }} group=nginx comment="added by ansible" system=yes state=present
  when: "'nginx' not in etc_groups.stdout_lines"

- name: install | role's package
  portage: package="{{ item }}" newuse=yes state=installed
  with_items:
    - "{{ nginx_packages }}"
