- name: Docker | x11docker directory
  ansible.builtin.file:
    path: /opt/x11docker
    state: directory
    mode: "0755"

- name: Docker | x11docker get
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker
    dest: /opt/x11docker/installer
    mode: "0755"

- name: Docker | x11docker install
  ansible.builtin.shell: /opt/x11docker/installer --update
  args:
    executable: /bin/bash

- name: Docker | install
  apt:
    package: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Docker | adding existing user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Docker | enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker
    - containerd

- name: Docker | data
  file:
    path: "{{ home }}/docker/{{ item[0] }}/{{ item[1] }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0755
    state: directory
  with_nested:
    - ["data", "dockerfiles"]
    - "{{ docker_images }}"

- name: Docker | deploy
  template:
    src: "docker/{{ item }}/Dockerfile.j2"
    dest: "{{ home }}/docker/dockerfiles/{{ item }}/Dockerfile"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0644"
  loop: "{{ docker_images }}"

- name: Docker | deploy | chrome extra directory
  file:
    path: "{{ home }}/docker/data/chrome/{{ item }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0755
    state: directory
  loop:
    - data
    - downloads

- name: Docker | deploy | yubikey extra
  template:
    src: "docker/yubikey/{{ item }}"
    dest: "{{ home }}/docker/dockerfiles/yubikey/{{ item}}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: "0644"
  loop:
    - gpg.pub
    - bashrc

- name: Docker | deploy | chrome local font
  template:
    src: "docker/chrome/local.conf"
    dest: "{{ home }}/docker/dockerfiles/chrome/local.conf"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644

- name: Docker | deploy | chrome seccomp
  template:
    src: "docker/chrome/seccomp.json"
    dest: "/etc/docker/seccomp-chrome.json"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644

- name: Docker | deploy | chrome volume rights
  file:
    path: "{{ home }}/docker/data/chrome/"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0775

- name: Docker | build
  ansible.builtin.shell: docker build . -f {{ home }}/docker/dockerfiles/{{ item }}/Dockerfile -t {{ docker_repo_prefix }}/{{ item }}:{{ docker_images_version }}
  loop: "{{ docker_images }}"
  args:
    executable: /bin/bash
