- name: elixir | install apt key
  ansible.builtin.apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: elixir | install apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.erlang-solutions.com/ubuntu xenial contrib"
    state: present

- name: elixir | packages
  apt:
    package: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - esl-erlang
    - elixir
