- name: neovim | ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: neovim | install
  apt:
    package: "{{ item }}"
    state: latest
  loop:
    - neovim

- name: neovim | configuration directory
  file:
    path: "{{ home }}/.config/nvim"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
    state: directory

- name: neovim | configuration directory lua
  file:
    path: "{{ home }}/.config/nvim/lua"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
    state: directory

- name: neovim | configuration directory lua plugins
  file:
    path: "{{ home }}/.config/nvim/lua/plugins"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
    state: directory

- name: neovim | files
  template:
    src: "{{ item.src }}"
    dest: "{{ home }}/{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0775
  loop:
    - {"src": "neovim/init.lua.j2", "dest": ".config/nvim/init.lua"}

- name: neovim | symlink
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    owner: root
    group: root
    state: link
