- name: rust | check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: rust | rustup
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: yes
  when: cargo_exists is failed

- name: rust | install
  shell: /tmp/sh.rustup.rs -y
  when: cargo_exists is failed

- name: rust | install rust-analyzer
  ansible.builtin.shell: |
    set -o pipefail rustup component add rust-analyzer
  args:
    executable: /bin/bash
