name: Patched YTDL

on: 
 push:
   branches:
     - master
 schedule:
   - cron:  "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install deps
      run: |
        sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
        sudo apt update
        sudo env DEBIAN_FRONTEND=noninteractive apt install -y curl zip make git gawk jq pandoc python python3 tzdata
    - name: Build patched YTDL
      run: |
        ./build.sh
    - name: Upload to gh-pages
      run: |
        git config --global user.name nao20010128nao
        git config --global user.email nao20010128@gmail.com
        git clone https://nao20010128nao:${{ secrets.GITHUB_PAT }}@github.com/nao20010128nao/ytdl-patched.git -b gh-pages gh-pages
        cd gh-pages
        cp ../artifacts/* .
        git add .
        git commit -m "$(date)"
        git push
